def save(itemList, planetid, name, health, damage, progress, regen, thrust, wepon, credits):
    f = open("SaveGame.txt", "w")
    f.write("")
    f.close()
    f = open("SaveGame.txt", "a")
    for x in itemList:
        f.write(x+ "\n")
    f.write("--end items--"+ "\n")
    f.write(str(planetid) + "\n")
    f.write(name + "\n")
    f.write(str(health)+ "\n")
    f.write(str(damage)+ "\n")
    f.write(str(progress)+ "\n")
    f.write(str(regen)+ "\n")
    f.write(str(thrust)+ "\n")
    f.write(str(wepon)+ "\n")
    f.write(str(credits)+ "\n")
    f.close()